//
//  PriceUnits.m
//
//  Generated by MTOPModelGenerator
//  Copyright (c) Taobao.com. All rights reserved.
//

#import "TBDetailPriceUnitsModel.h"

@implementation TBDetailPriceUnitsModel
-(TBDetailPriceUnitsModel *)deepCopy{
    TBDetailPriceUnitsModel *newModel = [TBDetailPriceUnitsModel alloc];
    newModel.tips = [self tips];
    newModel.display = [self display];
    newModel.name = [self name];
    newModel.price = [[self price]mutableCopy];
    return newModel;
}

-(instancetype)init{
    self = [super init];
//    self.prePayName = @"定金";
    return self;
}
@end