//
//  PriceUnitsTips.h
//
//  Generated by MTOPModelGenerator
//  Copyright (c) Taobao.com. All rights reserved.
//


#import "WeAppComponentBaseItem.h"

@protocol TBDetailTipsModel <NSObject>
@end

@interface TBDetailTipsModel : WeAppComponentBaseItem

//展示的文案
@property (nonatomic, copy) NSString *txt;

//点击对应的html
@property (nonatomic, copy) NSString *url;

//用于扩展的html
@property (nonatomic, copy) NSString *html;

//图片信息
@property (nonatomic, copy) NSString *logo;

//对应的样式
//key : bgcolor  value:#2B8CFF|#ff5000
@property (nonatomic , strong) NSDictionary *css;

@end
