//
//  SkuProps.m
//
//  Generated by MTOPModelGenerator
//  Copyright (c) Taobao.com. All rights reserved.
//

#import "TBDetailSkuPropsModel.h"

@implementation TBDetailSkuPropsModel

-(void)setFromDictionary:(NSDictionary *)dict{
    [super setFromDictionary:dict];
    if (self.propId == nil) {
        self.propId = [NSString stringWithFormat:@"%lu",(unsigned long)[self hash]];
    }
}


@end