//
//  SkuProps.h
//
//  Generated by MTOPModelGenerator
//  Copyright (c) Taobao.com. All rights reserved.
//


#import "WeAppComponentBaseItem.h"
#import "TBDetailSkuPropsValuesModel.h"

@protocol TBDetailSkuPropsModel <NSObject>
@end

@interface TBDetailSkuPropsModel : WeAppComponentBaseItem

//属性ID
@property (nonatomic, copy) NSString* propId;

//属性值列表;例如：颜色属性：红色，蓝色
@property (nonatomic, strong) NSArray<TBDetailSkuPropsValuesModel> *values;

//属性名称
@property (nonatomic, copy) NSString *propName;

@end
