//
//  TBDetailModel.m
//
//  Generated by MTOPModelGenerator
//  Copyright (c) Taobao.com. All rights reserved.
//

#import "TBDetailSKUModelAndService.h"

@implementation TBDetailSKUModelAndService

-(void)setFromDictionary:(NSDictionary *)dict{
    [super setFromDictionary:dict];
    self.skuService = [[TBTradeDetailSKUService alloc] initWithDetailResult:self];
}

@end