//
//  PriceUnits.h
//
//  Generated by MTOPModelGenerator
//  Copyright (c) Taobao.com. All rights reserved.
//


#import "WeAppComponentBaseItem.h"
#import "TBDetailTipsModel.h"

@protocol TBDetailPriceUnitsModel <NSObject>
@end

@interface TBDetailPriceUnitsModel : WeAppComponentBaseItem

//文案提示
@property (nonatomic, strong) NSArray<TBDetailTipsModel> *tips;
@property (nonatomic, strong) NSArray<TBDetailTipsModel> *tips2;

//展现的样式：1 ： 高亮显示 2 ： 普通显示 3 : 加删除线 (默认是删除的，设置了valid就有效)
@property (nonatomic, assign) NSInteger display;

//价格名字
@property (nonatomic, copy) NSString *name;

//价格 , 如： 1.00,100-102
@property (nonatomic, copy) NSString *price;

@property (nonatomic, copy) NSString *rangePrice;

//定金
@property (nonatomic, copy) NSString *prePayPrice;

//定金文案
@property (nonatomic, copy) NSString *prePayName;

-(TBDetailPriceUnitsModel *)deepCopy;
@end
