//
//  TBDetailModel.h
//
//  Generated by MTOPModelGenerator
//  Copyright (c) Taobao.com. All rights reserved.
//


#import "WeAppComponentBaseItem.h"
#import "TBDetailSkuModel.h"
#import "TBTradeDetailSKUService.h"

@protocol TBDetailSKUModelAndService <NSObject>

@end

@interface TBDetailSKUModelAndService : WeAppComponentBaseItem

//商品的sku相关信息
@property (nonatomic, strong) TBDetailSkuModel *skuModel;

//sku相关联动状态
@property (nonatomic, strong) TBTradeDetailSKUService *skuService;


@end
